apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travel-agency-role-binding
  namespace: travel-agency-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
